import styles from './Home.module.css';
import Card from '../../Components/Card/Card';

export default function Home() {
    return (
        <div className={styles.homeBody}>
            <h1>Home</h1>
            <p>asd asd asdasd sad sasdsa dsdssad sadsadsd sad asd</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus, dui ut vehicula laoreet, dui erat maximus magna, id lacinia turpis dui id dolor. Curabitur ornare nibh sed tempor mollis. Ut libero enim, laoreet non euismod in, dapibus et ante. Phasellus eget risus magna. Sed consequat pharetra massa, sit amet dapibus nisi efficitur eu. Integer nunc ligula, tempor non placerat sit amet, feugiat vel velit. Donec id tellus euismod, fringilla ipsum in, posuere elit. Quisque quis justo vehicula, molestie ex id, ultricies mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed luctus ut justo ut pulvinar</p>
            <p>Mauris sit amet hendrerit ex. Integer dictum purus metus, sed porta tortor rutrum eget. Praesent aliquam volutpat nisi, molestie mollis dolor euismod quis. Morbi rhoncus enim est. Vivamus fermentum nisi ante, non ultrices ex varius et. Sed ut tempus neque, ac sollicitudin ipsum. Fusce dui diam, fringilla et sodales eu, cursus sit amet eros. In bibendum ligula id felis iaculis, nec tincidunt neque suscipit. Aenean at venenatis arcu, a egestas felis. Nam dapibus purus varius sem interdum feugiat. Duis finibus tristique tellus eget rutrum. Phasellus pretium dolor ligula, ut interdum erat molestie ut. Nulla dolor ligula, tristique vel faucibus nec, ullamcorper ut sapien. Cras hendrerit nisi sed imperdiet sollicitudin.</p>
            <div className={styles.cards}>
                <Card title={"Introduction"} content={{p1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus, dui ut vehicula laoreet, dui erat maximus magna, id lacinia turpis dui id dolor. Curabitur ornare nibh sed tempor mollis. Ut libero enim, laoreet non euismod in, dapibus et ante. Phasellus eget risus magna. Sed consequat pharetra massa, sit amet dapibus nisi efficitur eu. Integer nunc ligula, tempor non placerat sit amet, feugiat vel velit. Donec id tellus euismod, fringilla ipsum in, posuere elit. Quisque quis justo vehicula, molestie ex id, ultricies mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed luctus ut justo ut pulvinar", p2:"Aliquam at auctor mauris, a dignissim enim. Mauris condimentum est non iaculis dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam cursus ligula est, sit amet vehicula sem volutpat ut. Morbi ac lectus mauris. Nam viverra ex non risus tincidunt tincidunt. Nulla facilisi. Nunc sagittis elit vitae sapien aliquet, ut maximus velit commodo.", img:"https://petapixel.com/assets/uploads/2024/01/The-Star-of-System-Sol-Rectangle-640x800.jpg", alt:"kep"}}></Card>
                <div className={styles.gap}></div>
                <Card title={"Introduction"} content={{p1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus, dui ut vehicula laoreet, dui erat maximus magna, id lacinia turpis dui id dolor. Curabitur ornare nibh sed tempor mollis. Ut libero enim, laoreet non euismod in, dapibus et ante. Phasellus eget risus magna. Sed consequat pharetra massa, sit amet dapibus nisi efficitur eu. Integer nunc ligula, tempor non placerat sit amet, feugiat vel velit. Donec id tellus euismod, fringilla ipsum in, posuere elit. Quisque quis justo vehicula, molestie ex id, ultricies mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed luctus ut justo ut pulvinar", p2:"fsanjdhnsaj kndjska ndjaskdn sajkdnasjkdn sajkdn jsan jknakjdnsdn jmgkremg er mgre kemgermi", img:"https://archive.smashing.media/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/68dd54ca-60cf-4ef7-898b-26d7cbe48ec7/10-dithering-opt.jpg", alt:"kep"}}></Card>
                <div className={styles.gap}></div>
                <Card title={"Introduction"} content={{p1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus, dui ut vehicula laoreet, dui erat maximus magna, id lacinia turpis dui id dolor. Curabitur ornare nibh sed tempor mollis. Ut libero enim, laoreet non euismod in, dapibus et ante. Phasellus eget risus magna. Sed consequat pharetra massa, sit amet dapibus nisi efficitur eu. Integer nunc ligula, tempor non placerat sit amet, feugiat vel velit. Donec id tellus euismod, fringilla ipsum in, posuere elit. Quisque quis justo vehicula, molestie ex id, ultricies mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed luctus ut justo ut pulvinar", p2:"fsanjdhnsaj kndjska ndjaskdn sajkdnasjkdn sajkdn jsan jknakjdnsdn jmgkremg er mgre kemgermi", img:"https://archive.smashing.media/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/68dd54ca-60cf-4ef7-898b-26d7cbe48ec7/10-dithering-opt.jpg", alt:"kep"}}></Card>
            </div>
            <p>In pharetra nunc ante. Curabitur convallis, nunc a sagittis auctor, sem ante posuere velit, eget vestibulum felis ipsum sit amet lacus. Aenean ex urna, consequat vestibulum porta sit amet, dapibus id nisl. Morbi accumsan volutpat nulla, in venenatis quam lobortis at. Curabitur in nulla sit amet quam rhoncus egestas eget in enim. Sed mollis tristique purus, ac varius neque pellentesque in. Ut faucibus sit amet dui quis vehicula. Ut enim lectus, pharetra eu lobortis at, blandit sit amet arcu. Suspendisse dignissim, lorem ut sollicitudin hendrerit, risus tortor dictum odio, posuere molestie arcu ligula vitae mi. Proin non luctus libero. Quisque suscipit felis a ultricies tristique. Nunc tristique sodales enim a efficitur. Nulla commodo justo dui, nec eleifend mauris sodales sit amet. Aenean diam neque, vestibulum quis feugiat eu, pretium et tellus.</p>
            <p>Etiam eleifend feugiat dui non placerat. Nam consequat sem at interdum scelerisque. Aliquam euismod leo imperdiet pretium euismod. Nulla rutrum metus scelerisque massa ornare, eget lobortis odio ornare. Duis odio nunc, malesuada ut imperdiet eu, dignissim vel lacus. Mauris et ipsum ut urna luctus vestibulum a vitae sem. Pellentesque laoreet venenatis aliquet.</p>
            <p>asd asd asdasd sad sasdsa dsdssad sadsadsd sad asd asdasdsadjsandjkn adkjsndjskadbvdhvasd asduiasgbduajsibgvzsddef fbgeuzg fuzesg fzesfegszufgesf bsuefzfgzduvbdscndsf ebnfjhesgbfd uzdsf ds bfsb dufhzbesfhjbsd fsdf</p>
            <p>asd asd asdasd sad sasdsa dsdssad sadsadsd sad asd</p>
            <p>Donec ac quam nec lectus ultrices elementum sit amet vel tortor. Proin eu accumsan arcu. Cras ultrices ligula vel ligula scelerisque, vel sollicitudin est interdum. Aliquam eleifend, elit quis rhoncus ullamcorper, dolor sem ultricies arcu, vel facilisis ipsum nisl nec lacus. Nunc metus augue, elementum at turpis et, dictum gravida ante. Aliquam erat volutpat. Curabitur convallis felis eu velit euismod, id viverra nulla dignissim. Pellentesque molestie lacinia sem, nec lacinia lorem scelerisque et. Praesent ac rutrum ipsum. Vestibulum laoreet tortor odio, at tempor elit pretium sit amet. Cras dignissim facilisis augue eget blandit.</p>
            <p>asd asd asdasd sad sasdsa dsdssad sadsadsd sad asd</p>
            <p>asd asd asdasd sad sasdsa dsdssad sadsadsd sad asd asdasdsadjsandjkn adkjsndjskadbvdhvasd asduiasgbduajsibgvzsddef fbgeuzg fuzesg fzesfegszufgesf bsuefzfgzduvbdscndsf ebnfjhesgbfd uzdsf ds bfsb dufhzbesfhjbsd fsdf</p>
            <p>asd asd asdasd sad sasdsa dsdssad sadsadsd sad asd</p>
            <p>asd asd asdasd sad sasdsa dsdssad sadsadsd sad asd asdasdsadjsandjkn adkjsndjskadbvdhvasd asduiasgbduajsibgvzsddef fbgeuzg fuzesg fzesfegszufgesf bsuefzfgzduvbdscndsf ebnfjhesgbfd uzdsf ds bfsb dufhzbesfhjbsd fsdf</p>
        </div>
    )
}